name: hi-visitor
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ github.actor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python env
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run script
        run: python3 hi.py
