name: hi-visitor
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python env
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Define env variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Run script
        run: python3 hi.py
