name: use secrets
run-name: secrets
on:
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  use_secret:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ github.actor }}
    steps:
      - name: using a secret value
        run: echo "Hi $USERNAME, your secret is ${{ secrets.CITY }}"
